analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 774648,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 759036,\\n  \\"status\\"\: \\"ACTIVE\\",\\n  \\"team\\"\: {\\n    \\"id\\"\: 759036,\\n    \\"name\\"\: \\"My Team\\",\\n    \\"organization\\"\: {\\n      \\"id\\"\: 656971,\\n      \\"name\\"\: \\"Organization stonetarigang\\",\\n      \\"samlSSO\\"\: false\\n    }\\n  },\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 759036,\\n  \\"name\\"\: \\"My Team\\",\\n  \\"organization\\"\: {\\n    \\"id\\"\: 656971,\\n    \\"name\\"\: \\"Organization stonetarigang\\",\\n    \\"samlSSO\\"\: false\\n  }\\n}"
analytics.testresult.autosubmit=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
